# Generated by Django 2.1.3 on 2019-01-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190114_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(max_length=100)),
                ('batting_team', models.CharField(max_length=250)),
                ('bowling_team', models.CharField(max_length=250)),
                ('over', models.IntegerField(max_length=100)),
                ('ball', models.IntegerField(max_length=100)),
                ('batsman', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('bowler', models.CharField(max_length=100)),
                ('is_super_over', models.IntegerField(max_length=100)),
                ('wide_runs', models.IntegerField(max_length=100)),
                ('bye_runs', models.IntegerField(max_length=100)),
                ('legbye_runs', models.IntegerField(max_length=100)),
                ('noball_runs', models.IntegerField(max_length=100)),
                ('penalty_runs', models.IntegerField(max_length=100)),
                ('batsman_runs', models.IntegerField(max_length=100)),
                ('extra_runs', models.IntegerField(max_length=100)),
                ('total_runs', models.IntegerField(max_length=100)),
                ('player_dismissed', models.CharField(max_length=100)),
                ('dismissal_kind', models.CharField(max_length=100)),
                ('fielder', models.CharField(max_length=100)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Matches')),
            ],
        ),
    ]
